export const programacionData = [
      {
        id: 1,
        unidad: "MSDU 254163-5",
        producto: "CERAMICA",
        almacen: "B2B",
        nave: "MSC CANDIDA",
        depot: "CIS COLENGUAO",
      },
      {
        id: 2,
        unidad: "TEMU 784512-3",
        producto: "CERAMICA",
        almacen: "B2B",
        nave: "MSC CANDIDA",
        depot: "CIS COLENGUAO",
      },
      {
        id: 3,
        unidad: "FSCU 998741-0",
        producto: "CERAMICA",
        almacen: "B2B",
        nave: "MSC CANDIDA",
        depot: "CIS COLENGUAO",
      },
      {
        id: 4,
        unidad: "HLBU 456321-8",
        producto: "CERAMICA",
        almacen: "B2B",
        nave: "MSC CANDIDA",
        depot: "CIS COLENGUAO",
      },
      {
        id: 5,
        unidad: "MSCU 332145-6",
        producto: "CERAMICA",
        almacen: "RETAIL",
        nave: "MSC CANDIDA",
        depot: "CIS COLENGUAO",
      },
      {
        id: 6,
        unidad: "FSCU 552145-6",
        producto: "CERAMICA",
        almacen: "RETAIL",
        nave: "MSC CANDIDA",
        depot: "CIS COLENGUAO",
      },
      {
        id: 7,
        unidad: "CMAU 159753-4",
        producto: "SANITARIOS",
        almacen: "FULL",
        nave: "CMA CGM ELLE",
        depot: "SITRANS SAI",
      },
    ];